### ISSUE TITLE
Create a tutorial to use Pycharm as volttron development environment

### ISSUE THREAD

**Issue by kefeimo** [kefeimo/dev-volttron-modular#1]
Create a tutorial to use Pycharm as volttron development environment

**Comment by kefeimo** [comment]
# Development VOLTTRON using platform driver development as an example

### Ref:

- VOLTTRON read-the-doc V8: **[Pycharm** Development Environment](https://volttron.readthedocs.io/en/main/developing-volttron/development-environment/pycharm/index.html?highlight=agent%20develop%20pycharm)
- run-agent-script: [[launch-agent.py](https://github.com/kefeimo/dev-volttron-modular/blob/develop/volttron/scripts/launch-agent.py)](https://github.com/kefeimo/dev-volttron-modular/blob/develop/volttron/scripts/launch-agent.py) (commit: https://github.com/kefeimo/dev-volttron-modular/commit/1784a40f529168eca77bf06a808ec11b262d69ce)

AGENT_CONFIG=/home/kefei/project/dev-volttron-modular/volttron-platform-driver/config \
AGENT_VIP_IDENTITY=platform_driver_20 \
VOLTTRON_HOME=/home/kefei/.dev-volttron-2 \
/home/kefei/project/dev-volttron-modular/env/bin/python \
/home/kefei/project/dev-volttron-modular/volttron/scripts/launch-agent.py \
/home/kefei/project/dev-volttron-modular/volttron-platform-driver/src/platform_driver/agent.py

### Run volttron instance

prerequisite:

- create a virtual env, e.g., called `env`, e.g., (at the desired path) `python -m venv env`
- install volttron, e.g., `pip install volttron`

Configuration

![image](https://user-images.githubusercontent.com/28743873/235402580-f4aaaf7a-51c8-4bd2-a005-67363914cbd5.png)

To Run:

![image](https://user-images.githubusercontent.com/28743873/235402421-96caac3b-8f25-4499-9709-6c10ce83db15.png)

Result:

![image](https://user-images.githubusercontent.com/28743873/235402682-01f25793-ac17-4994-885d-889911b89cd4.png)

Explanation:

This is almost to equally run `volttron -v` (with `export VOLTTRON_HOME=/home/kefei/.dev-volttron-2`)

Or Equally to run the following

```bash
VOLTTRON_HOME=/home/kefei/.dev-volttron-2 \
/home/kefei/project/dev-volttron-modular/env/bin/python \
/home/kefei/project/dev-volttron-modular/env/bin/volttron -v
```

result

```bash
kefei@ubuntu-22:~$ VOLTTRON_HOME=/home/kefei/.dev-volttron-2 /home/kefei/project/dev-volttron-modular/env/bin/python /home/kefei/project/dev-volttron-modular/env/bin/volttron -v 
2023-04-30 11:33:34,371 () volttron.utils.context(150) WARNING: Using hostname as instance name.
2023-04-30 11:33:34,371 () volttron.utils.context(150) WARNING: Using hostname as instance name.
2023-04-30 11:33:34,371 () volttron.utils.context(150) WARNING: Using hostname as instance name.
2023-04-30 11:33:34,371 () volttron.utils.context(150) WARNING: Using hostname as instance name.
2023-04-30 11:33:34,371 () volttron.server.__main__(247) WARNING: insecure mode on directory: /home/kefei/.dev-volttron-2
2023-04-30 11:33:35,378 () volttron.types.server_config(86) WARNING: Couldn't load volttron.services.routing
2023-04-30 11:33:35,379 () volttron.types.server_config(121) INFO: Creating volttron.services.auth
2023-04-30 11:33:35,381 () volttron.types.server_config(121) INFO: Creating volttron.services.config_store
2023-04-30 11:33:35,381 () volttron.types.server_config(121) INFO: Creating volttron.services.control
2023-04-30 11:33:35,382 () volttron.types.server_config(121) INFO: Creating volttron.services.health
2023-04-30 11:33:35,383 () volttron.services.config_store.config_store_service(121) INFO: Initializing configuration store service.
2023-04-30 11:33:35,385 () volttron.services.auth.auth_service(172) INFO: loading auth file /home/kefei/.dev-volttron-2/auth.json
2023-04-30 11:33:35,386 () volttron.services.auth.auth_service(193) INFO: auth file /home/kefei/.dev-volttron-2/auth.json loaded
2023-04-30 11:33:35,386 () volttron.utils.filewatch(98) INFO: Adding file watch for /home/kefei/.dev-volttron-2/auth.json dirname=/home/kefei/.dev-volttron-2, filename=auth.json
2023-04-30 11:33:35,387 () volttron.utils.filewatch(110) INFO: Added file watch for /home/kefei/.dev-volttron-2/auth.json
2023-04-30 11:33:35,387 () volttron.utils.filewatch(98) INFO: Adding file watch for /home/kefei/.dev-volttron-2/protected_topics.json dirname=/home/kefei/.dev-volttron-2, filename=protected_topics.json
2023-04-30 11:33:35,387 () volttron.utils.filewatch(110) INFO: Added file watch for /home/kefei/.dev-volttron-2/protected_topics.json
2023-04-30 11:33:35,388 () volttron.services.routing.pubsub_service(636) INFO: protected-topics loaded
2023-04-30 11:33:35,388 () volttron.client.vip.agent.core(619) INFO: Connected to platform: identity: platform.config_store version: 1.0
2023-04-30 11:33:35,391 () volttron.client.vip.agent.core(619) INFO: Connected to platform: identity: platform.auth version: 1.0
2023-04-30 11:33:35,393 () volttron.services.routing.pubsub_service(636) INFO: protected-topics loaded
2023-04-30 11:33:35,491 () volttron.client.vip.agent.core(619) INFO: Connected to platform: identity: platform.control version: 1.0
2023-04-30 11:33:35,494 () volttron.client.vip.agent.core(619) INFO: Connected to platform: identity: platform.health version: 1.0
2023-04-30 11:33:35,495 () volttron.services.auth.auth_service(172) INFO: loading auth file /home/kefei/.dev-volttron-2/auth.json
^CKeyboardInterrupt
2023-04-30T16:33:36Z
2023-04-30 11:33:36,679 () volttron.server.__main__(507) INFO: SIGINT received; shutting down
Shutting down.
```

Note: for volttron==10.0.2rc0, the VOLTTRON_HOME environment variable is required.

Extra Notes: 

- **[[What exactly is current working directory?](https://stackoverflow.com/questions/45591428/what-exactly-is-current-working-directory)](https://stackoverflow.com/questions/45591428/what-exactly-is-current-working-directory)**
- **[[How to set up working directory in PyCharm and package ...](https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000782850-How-to-set-up-working-directory-in-PyCharm-and-package-import-)](https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000782850-How-to-set-up-working-directory-in-PyCharm-and-package-import-)**

Bonus Tips: How do we know if a volttron instance is running

Option 1: `ps aux | grep volttron`

```bash
# NOT RUNNING
(env) kefei@ubuntu-22:~/project/dev-volttron-modular$ ps aux | grep volttron
kefei       3430  0.0  0.0   9208  2428 pts/1    S+   11:41   0:00 grep --color=auto volttron

# RUNNING
(env) kefei@ubuntu-22:~/project/dev-volttron-modular$ ps aux | grep volttron
kefei       3441  6.6  0.5 734816 42676 pts/3    Sl+  11:42   0:00 /home/kefei/project/dev-volttron-modular/env/bin/python /home/kefei/project/dev-volttron-modular/env/bin/volttron -v
kefei       3456  0.0  0.0   9208  2428 pts/1    S+   11:42   0:00 grep --color=auto volttron
```

Option 2: `vctl status` (need to make sure the $VOLTTRON_HOME is set properly) 

```bash
(env) kefei@ubuntu-22:~/project/dev-volttron-modular$ echo $VOLTTRON_HOME
~/.dev-volttron-2

# NOT RUNNING
(env) kefei@ubuntu-22:~/project/dev-volttron-modular$ vctl status
VOLTTRON is not running. This command requires VOLTTRON platform to be running

# RUNNING
(env) kefei@ubuntu-22:~/project/dev-volttron-modular$ vctl status
No installed Agents found
```

### Run VOLTTRON agent (use platform-driver as an example)

Motivation:

- (assuming the scenario is development)
- More explicit, more pythonic
    - direct control on the agent life cycle, e.g., NO `vctl start` invovled
    - change take effect on-the-fly, NO `vctl install` involved

prerequisite:

- git clone repo, e.g., (at a desired path) `git clone [https://github.com/eclipse-volttron/volttron-platform-driver.git](https://github.com/eclipse-volttron/volttron-platform-driver.git)`
- Have the [[launch-agent.py](https://github.com/kefeimo/dev-volttron-modular/blob/develop/volttron/scripts/launch-agent.py)](https://github.com/kefeimo/dev-volttron-modular/blob/develop/volttron/scripts/launch-agent.py)  available
- volttron instance running (see earlier session, or use alternative working solutions)

Configuration:

![image](https://user-images.githubusercontent.com/28743873/235403213-c9dc58fd-4733-4ccc-872e-b910a86bee0a.png)

(continued) 

![image](https://user-images.githubusercontent.com/28743873/235403242-861e15cf-1a41-4f94-8ee8-394ead06e182.png)

```bash
AGENT_CONFIG=/home/kefei/project/dev-volttron-modular/volttron-platform-driver/config;AGENT_VIP_IDENTITY=platform_driver_20;PYTHONUNBUFFERED=1;VOLTTRON_HOME=/home/kefei/.dev-volttron-2
```

Result

![image](https://user-images.githubusercontent.com/28743873/235403262-9dc4db8c-16cb-4919-a467-d94798814ef8.png)

Again, the volttron instance needs to be running, otherwise the agent will stop

![image](https://user-images.githubusercontent.com/28743873/235403289-d98fa82e-e9b6-44aa-a849-ce228cfdb96a.png)

Explanation

It contains the following parts

- environment variable setting (all required)
    - VOLTTRON_HOME (required to map to the running volttron instance)
    - AGENT_VIP_IDENTITY (required by the [[launch-agent.py](http://launch-agent.py/)](http://launch-agent.py) script, see [https://github.com/kefeimo/dev-volttron-modular/blob/develop/volttron/scripts/launch-agent.py#L98](https://github.com/kefeimo/dev-volttron-modular/blob/develop/volttron/scripts/launch-agent.py#L98))
    - AGENT_CONFIG (required by the [[launch-agent.py](http://launch-agent.py/)](http://launch-agent.py) script, the actual content depends on individual agent, see [https://github.com/kefeimo/dev-volttron-modular/blob/develop/volttron/scripts/launch-agent.py#L98](https://github.com/kefeimo/dev-volttron-modular/blob/develop/volttron/scripts/launch-agent.py#L6). For this version of the platform driver, you can use [[config](https://github.com/kefeimo/dev-volttron-modular/blob/develop/volttron-platform-driver/config)](https://github.com/kefeimo/dev-volttron-modular/blob/develop/volttron-platform-driver/config),)
- python executable, e.g., `env/bin/python`
- the path to [[launch-agent.py](https://github.com/kefeimo/dev-volttron-modular/blob/develop/volttron/scripts/launch-agent.py)](https://github.com/kefeimo/dev-volttron-modular/blob/develop/volttron/scripts/launch-agent.py)
- the path o the [[agent.py](http://agent.py/)](http://agent.py) file which define the agent’s core functionality following Volttron agent skeleton (more details please see **[Agent** Development](https://volttron.readthedocs.io/en/main/developing-volttron/developing-agents/agent-development.html?highlight=agent%20develop))

Equally to run the following from the command line

```bash
AGENT_CONFIG=/home/kefei/project/dev-volttron-modular/volttron/examples/ListenerAgent/config \
AGENT_VIP_IDENTITY=platform_driver_20 \
VOLTTRON_HOME=/home/kefei/.dev-volttron-2 \
/home/kefei/project/dev-volttron-modular/env/bin/python \
/home/kefei/project/dev-volttron-modular/volttron/scripts/launch-agent.py \
/home/kefei/project/dev-volttron-modular/volttron-platform-driver/src/platform_driver/agent.py
```

result

```bash
kefei@ubuntu-22:~$ AGENT_CONFIG=/home/kefei/project/dev-volttron-modular/volttron/examples/ListenerAgent/config AGENT_VIP_IDENTITY=platform_driver_20 VOLTTRON_HOME=/home/kefei/.dev-volttron-2 /home/kefei/project/dev-volttron-modular/env/bin/python /home/kefei/project/dev-volttron-modular/volttron/scripts/launch-agent.py /home/kefei/project/dev-volttron-modular/volttron-platform-driver/src/platform_driver/agent.py
============ agent_identity platform_driver_20
For your information (-s) to not print this message.Required Environment Variables
    AGENT_VIP_IDENTITY - Required 
Optional Environmental Variables
    AGENT_CONFIG            - Set to <agent directory>/config by default
    VOLTTRON_HOME           - Set to ~/.volttron by default
2023-04-30 11:57:18,787 __main__ DEBUG: open file resource limit increased from 1024 to 1048576
2023-04-30 11:57:18,787 root DEBUG: Creating ZMQ Core platform_driver_20
2023-04-30 11:57:18,788 volttron.client.vip.agent.core DEBUG: address: ipc://@/home/kefei/.dev-volttron-2/run/vip.socket
2023-04-30 11:57:18,788 volttron.client.vip.agent.core DEBUG: identity: platform_driver_20
2023-04-30 11:57:18,788 volttron.client.vip.agent.core DEBUG: agent_uuid: None
2023-04-30 11:57:18,788 volttron.client.vip.agent.core DEBUG: serverkey: None
2023-04-30 11:57:18,788 volttron.client.vip.agent.core DEBUG:  environ keys: dict_keys(['VOLTTRON_HOME', 'AGENT_VIP_IDENTITY', 'AGENT_CONFIG', 'SHELL', 'SESSION_MANAGER', 'QT_ACCESSIBILITY', 'COLORTERM', 'XDG_CONFIG_DIRS', 'SSH_AGENT_LAUNCHER', 'XDG_MENU_PREFIX', 'GNOME_DESKTOP_SESSION_ID', 'CONDA_EXE', '_CE_M', 'GNOME_SHELL_SESSION_MODE', 'SSH_AUTH_SOCK', 'HOMEBREW_PREFIX', 'XMODIFIERS', 'DESKTOP_SESSION', 'GTK_MODULES', 'PWD', 'LOGNAME', 'XDG_SESSION_DESKTOP', 'XDG_SESSION_TYPE', 'MANPATH', 'SYSTEMD_EXEC_PID', 'XAUTHORITY', 'HOME', 'USERNAME', 'IM_CONFIG_PHASE', 'LANG', 'LS_COLORS', 'XDG_CURRENT_DESKTOP', 'VTE_VERSION', 'WAYLAND_DISPLAY', 'GNOME_TERMINAL_SCREEN', 'INFOPATH', 'GNOME_SETUP_DISPLAY', 'LESSCLOSE', 'XDG_SESSION_CLASS', 'TERM', '_CE_CONDA', 'LESSOPEN', 'USER', 'HOMEBREW_CELLAR', 'GNOME_TERMINAL_SERVICE', 'CONDA_SHLVL', 'DISPLAY', 'SHLVL', 'QT_IM_MODULE', 'HOMEBREW_REPOSITORY', 'CONDA_PYTHON_EXE', 'XDG_RUNTIME_DIR', 'XDG_DATA_DIRS', 'PATH', 'GDMSESSION', 'DBUS_SESSION_BUS_ADDRESS', '_', 'AGENT_PUBLICKEY', 'AGENT_SECRETKEY', 'RABBITMQ_NOT_AVAILABLE'])
2023-04-30 11:57:18,788 volttron.client.vip.agent.core DEBUG: server key from env None
2023-04-30 11:57:18,788 volttron.client.vip.agent.core DEBUG: AGENT RUNNING on ZMQ Core platform_driver_20
2023-04-30 11:57:18,789 volttron.client.vip.agent.core DEBUG: keys: server: 9OgdApgnfmYBb191j7lriGKJ3Rw8JnfeEDmD0VUNVk4 public: Wrwyjz3p8YEKKODGdfF8Kd5yaCMh9dN1TgkqhCarTHQ, secret: wJsgkUJB9ftSg8GT3pZmG-ACqoU8INfbGvCct4UmDbQ
2023-04-30 11:57:18,790 volttron.client.vip.zmq_connection DEBUG: ZMQ connection platform_driver_20
2023-04-30 11:57:18,790 volttron.client.vip.zmq_connection DEBUG: connecting to url ipc://@/home/kefei/.dev-volttron-2/run/vip.socket?publickey=Wrwyjz3p8YEKKODGdfF8Kd5yaCMh9dN1TgkqhCarTHQ&secretkey=wJsgkUJB9ftSg8GT3pZmG-ACqoU8INfbGvCct4UmDbQ&serverkey=9OgdApgnfmYBb191j7lriGKJ3Rw8JnfeEDmD0VUNVk4
2023-04-30 11:57:18,790 volttron.client.vip.zmq_connection DEBUG: url type is <class 'str'>
2023-04-30 11:57:18,794 volttron.client.vip.agent.core INFO: Connected to platform: identity: platform_driver_20 version: 1.0
2023-04-30 11:57:18,794 volttron.client.vip.agent.core DEBUG: Running onstart methods.
2023-04-30 11:57:18,805 volttron.client.vip.agent.subsystems.configstore DEBUG: Processing callbacks for affected files: {'dnp3.csv': 'NEW', 'devices/campus/building/dnp3': 'NEW', 'config': 'NEW'}
2023-04-30 11:57:18,805 __main__ INFO: maximum concurrently open sockets limited to 838860 (derived from system limits)
2023-04-30 11:57:18,805 __main__ INFO: maximum concurrent driver publishes limited to 10000
2023-04-30 11:57:18,805 __main__ INFO: In update_driver
2023-04-30 11:57:18,805 __main__ INFO: Starting driver: campus/building/dnp3
2023-04-30 11:57:18,805 volttron.driver.base.driver DEBUG: campus/building/dnp3 group: 0, time_slot: 0, offset: 0.0
===============driver
driver <volttron.driver.base.driver.DriverAgent object at 0x7fa8cc175990>
dir(dirver) ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_publish_wrapper', 'config', 'core', 'device_name', 'device_path', 'find_starting_datetime', 'get_driver_module', 'get_interface', 'get_multiple_points', 'get_paths_for_point', 'get_point', 'group', 'heart_beat', 'heart_beat_value', 'interval', 'parent', 'periodic_read', 'periodic_read_event', 'publish_breadth_first', 'publish_breadth_first_all', 'publish_cov_value', 'publish_depth_first', 'publish_depth_first_all', 'revert_all', 'revert_point', 'scrape_all', 'set_multiple_points', 'set_point', 'setup_device', 'starting', 'time_slot', 'time_slot_offset', 'update_publish_types', 'update_scrape_schedule', 'vip']
dir(topic) campus/building/dnp3
dir(group) 0
dir(config_name) devices/campus/building/dnp3
```

Note: verify if the agent is running

As mentioned earlier, in this run agent workflow, we didn’t install the agent/register agent to the VOLTTRON_HOME path, hence we cannot use either `vctl status` or `vctl list` to view the running agents. Instead use `vctl peerlist`

```bash
(env) kefei@ubuntu-22:~/project/dev-volttron-modular$ vctl status
No installed Agents found
(env) kefei@ubuntu-22:~/project/dev-volttron-modular$ vctl list
No installed Agents found
(env) kefei@ubuntu-22:~/project/dev-volttron-modular$ vctl peerlist
control.connection
platform.auth
platform.config_store
platform.control
platform.health
platform_driver_20
```

### Note: can we add brake points in [agent.py](http://agent.py/)?

Normally as a Python developer we would like to add brake points in the script and have the runnable stop there, however this is not how [[launch-agent.py](http://launch-agent.py/)](http://launch-[agent.py](http://agent.py/)) works. Long story short, we cannot add breakpoints in agent.py and expect the program to stop there. That can be a gotcha we have to keep in mind.

### Bonus: evoke RPC calls using a vip agent.

rpc call is an important pattern to evoke agent’s function and provide flexibility outside the standard volttron agent life cycle methods. Following is an example to configure and run a rpc agent, and evoke an agent dummy method

```python
# in /volttron-platform-driver/src/platform_driver/agent.py

class PlatformDriverAgent(Agent):
# ...
	@RPC.export
	    def dummy(self):
	        return "this is a dummy method."
```

```python
from volttron.client.vip.agent import build_agent

def main():

    a = build_agent()
    res = a.vip.peerlist().get()
    print(f"======= a.vip.peerlist().get(), {res}")

    res = a.vip.rpc.call("platform_driver_20", "dummy").get(5)
    print(f"======= a.vip.rpc.call dummy, {res}")

    res = a.vip.rpc.call("platform_driver_20", "dummy8").get(5)
    print(f"======= a.vip.rpc.call dummy, {res}")

if __name__ == "__main__":
    main()
```

Result

```bash
/home/kefei/project/dev-volttron-modular/env/bin/python /home/kefei/project/dev-volttron-modular/tmp/rpc-example.py 
======= a.vip.peerlist().get(), ['platform.config_store', 'platform.health', 'platform.control', '4d0423dc-487e-41c2-8990-4ce990442257', 'platform.auth', 'platform_driver_20']
======= a.vip.rpc.call dummy, this is a dummy method.
Traceback (most recent call last):
  File "/home/kefei/project/dev-volttron-modular/tmp/rpc-example.py", line 18, in <module>
    main()
  File "/home/kefei/project/dev-volttron-modular/tmp/rpc-example.py", line 13, in main
    res = a.vip.rpc.call("platform_driver_20", "dummy8").get(5)
  File "src/gevent/event.py", line 329, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 359, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 329, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 329, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 347, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 327, in gevent._gevent_cevent.AsyncResult._raise_exception
  File "/home/kefei/project/dev-volttron-modular/env/lib/python3.10/site-packages/gevent/_compat.py", line 66, in reraise
    raise value
volttron.utils.jsonrpc.MethodNotFound: method 'dummy8' is not implemented

Process finished with exit code 1
```

More details please see 

- [Platforms Agents **RPC** Endpoints](https://volttron.readthedocs.io/en/main/platform-features/web-api/platforms/agents/rpc-endpoints.html?highlight=rpc)
- [vctl **rpc** Subcommands](https://volttron.readthedocs.io/en/main/platform-features/control/platform-commands.html?highlight=rpc#vctl-rpc-subcommands)
- [Why JSON-**RPC**](https://volttron.readthedocs.io/en/main/agent-framework/core-service-agents/volttron-central/webservice-api.html?highlight=rpc#why-json-rpc)

**Comment by kefeimo** [comment]
Finished and hence closed
